### ISSUE TITLE
Globe window resize doesn't resize background.

### ISSUE THREAD

**Issue by sk222sw** [Visualisering/Visualisering-frontend#41]
Changing the size of the browser window doesn't change the background size in the globe module visualization, i.e going into fullscreen mode will add a white area in the bottom.

**Comment by fyrkant** [comment]
Yep, in the current implementation the size of the globe visualization is just set on page load by reading the width and size off of `window`, in this file: https://github.com/Visualisering/Visualisering-frontend/blob/master/src/utils/three-utils.js

This can be fixed in several ways, I even think that react has a onPageResize or something like that where the size could be recalculated, but the real question is if it is necessary? I think that the visualization will be run in full-screen all the time? Of course it might be nice to fix regardless!

**Comment by fyrkant** [comment]
Yeah this should probably help fixing this: https://facebook.github.io/react/tips/dom-event-listeners.html

**Comment by sk222sw** [comment]
As long as the window height/weight variables are assigned after going into fullscreen and we're only displaying this module it should be ok i guess. But what happens if we split-screen two visualizations?

I'm not sure how probable it is, but there might be situations in the future where someone wants to automate going from split-screen to fullscreen without reloading, or something like that.

Fixing this isn't that hard, I'd say it's worth the time.

**Comment by rpkarlsson** [comment]
Yeah, i need the size when declaring how big the webgl rendering will be.
Seems an event listener will be the way to go. Just resizing with css will not trigger a change to the webgl rendered size. Any changes to the element containing the 3d viewport will not affect the viewport itself.

Fixing dynamic resizing of the webgl viewport is doable. It just isn't a priority for me at the moment. As we, at the moment, lack any solution to display many visualizations side by side.

As for the white border. I can make the wrapper black for the moment until we add a event listener to trigger a resize of the webgl viewport upon changes to the dom.
